name: cats_challenge
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0

  #logging
  logger: ^2.0.2+1

  #state mgmt
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #functional prog
  fpdart: ^1.1.0

  #routing
  auto_route: ^7.8.4  

  #api calls
  dio: ^5.3.3

  #local db
  sembast: ^3.5.0+1
  path_provider: ^2.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #injection and code gen
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  injectable_generator: ^2.4.1

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

